
server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://192.168.10.67:3306/ddw_base?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
# 指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:dao/*.xml
  configuration:
    call-setters-on-nulls: true
    cache-enabled: false
    lazy-loading-enabled: false